"""add lab_completions

Revision ID: ea90a8d9b101
Revises: 9cbd9d1457c5
Create Date: 2026-10-07 10:42:55.473445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# NOTE (2026-10-07): this migration originally had down_revision '9cbd9d1457c5'
# because b7f3a1c9d2e4_add_lab_sessions.py had been deleted from the repo while
# still applied to the production database ("Can't locate revision" crash loop).
# The deleted migration was restored, and this one re-chained onto it.
# Migrations are append-only: never delete one that has been applied anywhere.
revision: str = 'ea90a8d9b101'
down_revision: Union[str, Sequence[str], None] = 'b7f3a1c9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_completions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_lab_completion_session')
    )
    op.create_index(op.f('ix_lab_completions_completed_at'), 'lab_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_lab_completions_lab_id'), 'lab_completions', ['lab_id'], unique=False)
    op.create_index(op.f('ix_lab_completions_user_id'), 'lab_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_completions_user_id'), table_name='lab_completions')
    op.drop_index(op.f('ix_lab_completions_lab_id'), table_name='lab_completions')
    op.drop_index(op.f('ix_lab_completions_completed_at'), table_name='lab_completions')
    op.drop_table('lab_completions')
    # ### end Alembic commands ###
